server.port=8080
spring.application.name=Service Request Workflow Engine
flowable.process-definition-location-prefix=classpath:bpmn/
flowable.check-process-definitions=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
app.sla.triage=15
app.sla.assign=30
app.sla.work=480
app.sla.review=60
app.assignment.max-capacity=5
app.assignment.default-strategy=SKILL_LOAD_BALANCE
app.notifications.enabled=true
